version: '3.7'

name: cubes5

services:
  main:
    build:
      context: .
      dockerfile: DockerfileMain
    container_name: lamp_main
    restart: always
    ports:
      - "8081:80"
    volumes:
      - main:/var/www/html
    networks:
      - lamp-network

  stage:
    build:
      context: .
      dockerfile: DockerfileStage
    container_name: lamp_stage
    restart: always
    ports:
      - "80:80"
    volumes:
      - stage:/var/www/html
    networks:
      - lamp-network

  db:
    image: mysql:8.0
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - lamp-network

networks:
  lamp-network:

volumes:
  db_data:
  stage:
  main: